name: eShopOnWeb CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE-GROUP: 'rg-eshoponweb-YORLI'
  LOCATION: 'East US' # e.g., 'eastus'
  SUBSCRIPTION-ID: 'adfd373c-b356-4191-9cac-eec1d37d1104'
  WEBAPP-NAME: 'yorli-workflow'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src
        
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: src
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: src
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src
        
      - name: Publish
        run: dotnet publish --no-restore --configuration Release --output ./output
        working-directory: src
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP-NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./output
